services:
  postgres:
    image: postgres:15
    container_name: stock_pipeline_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready","-U","airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
  
volumes:
  postgres_data:

