services:

  postgres:
    image: postgres:15
    container_name: stock_pipeline_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  airflow-init:
    image: apache/airflow:2.8.1
    container_name: stock_pipeline_airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        airflow users create \
          --username admin \
          --password admin \
          --firstname Vaishnavi \
          --lastname Kashyap \
          --role Admin \
          --email admin@stockpipeline.com
    restart: on-failure

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: stock_pipeline_airflow_webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}
      STOCK_DB_HOST: postgres
      STOCK_DB_PORT: 5432
      STOCK_DB_NAME: stocks
      STOCK_DB_USER: airflow
      STOCK_DB_PASSWORD: airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./dbt/stock_mart:/opt/airflow/dbt_project
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: stock_pipeline_airflow_scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}
      STOCK_DB_HOST: postgres
      STOCK_DB_PORT: 5432
      STOCK_DB_NAME: stocks
      STOCK_DB_USER: airflow
      STOCK_DB_PASSWORD: airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./dbt/stock_mart:/opt/airflow/dbt_project
    command: scheduler
    restart: always

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.0
    container_name: stock_pipeline_dbt
    volumes:
      - ./dbt/stock_mart:/usr/app/dbt
    environment:
      - DBT_PROFILES_DIR=/usr/app/dbt
    working_dir: /usr/app/dbt
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - dbt
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: stock_pipeline_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD","nc","-z","localhost","2181"]
      interval: 10s
      retries: 5
      start_period: 10s
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: stock_pipeline_kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_LOG_RETENTION_HOURS: 24
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 15s
      retries: 5
      start_period: 20s
    restart: always
  
  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    container_name: stock_pipeline_kafka_init
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        echo 'Creating Kafka topics...'

        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists \
          --topic stock.intraday.quotes \
          --partitions 10 \
          --replication-factor 1 \
          --config retention.ms=86400000

        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists \
          --topic stock.intraday.quotes.dlq \
          --partitions 1 \
          --replication-factor 1 \
          --config retention.ms=604800000

        echo 'Topics created:'
        kafka-topics --bootstrap-server kafka:9092 --list
    restart: on-failure
    
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: stock_pipeline_kafka_ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: stock-pipeline
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    restart: always
      
volumes:
  postgres_data: